apiVersion: v1
kind: ReplicationController
metadata:
  name: netcore-dockerlinux
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: netcore-dockerlinux
    spec:
      containers:
      - name: netcore-dockerlinux
        image: leixu.azurecr.io/netcore-dockerlinux:v1
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: leixuacr
---
apiVersion: v1
kind: Service
metadata:
  name: netcore-dockerlinux
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: netcore-dockerlinux